version: "3.2"
name: url-shortener
services:
  
  url-shortener:
    container_name: url-shortener
    image: url-shortener
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_HOST=database
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - MODE=${MODE}
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - url-shortener-network
    volumes:
      - ./src:/app/src

  database:
    container_name: database
    image: postgres:14.5
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - url-shortener-network
    volumes:
      - database:/var/lib/postgresql/data


networks:
  url-shortener-network:
    name: url-shortener-network
    driver: bridge

volumes:
  database: