version: "3"
name: url-shortener
services:
  
  url-shortener:
    container_name: url-shortener
    image: url-shortener
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - url-shortener-network

  database:
    container_name: database
    image: postgres:14.5
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - url-shortener-network
    volumes:
      - database:/.data


networks:
  url-shortener-network:
    name: url-shortener-network
    driver: bridge

volumes:
  database: